apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapi-deployment
spec:
  selector:
    matchLabels:
      app: demoapi
  replicas: 1
  template:
    metadata:
      labels:
        app: demoapi
    spec:
      containers:
      - name: demoapi
        image: IMAGE_URL
        ports:
        - containerPort: 8000
